language: minimal
sudo: true

addons:
  apt:
    packages:
      - luarocks

install:
  - luarocks install --local luacheck
  - sudo luarocks install luafilesystem
  - sudo luarocks install penlight

script:
  - |
    if [ "$TRAVIS_BRANCH" == "master" -o -n "$TRAVIS_TAG" ]; then
      /home/travis/.luarocks/bin/luacheck . --exclude-files 'DRList-1.0/libs/LibStub/LibStub.lua'
      lua DRList-1.0/tests/test.lua
    fi

  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a -n "$TRAVIS_TAG" ]; then
      rm -rf DRList-1.0/libs # libs/ is kept before so tests.lua works, but we need to remove it here to make nolib-creation work with packager script below
      curl -L -s https://github.com/stevedonovan/LDoc/archive/1.4.6.tar.gz | tar -xz
      lua LDoc-1.4.6/ldoc.lua DRList-1.0/DRList-1.0.lua # has to be triggered from root folder
      cd DRList-1.0
      curl -L -s -o release.sh https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh
      chmod +x ./release.sh
      ./release.sh -g 1.13.2 # classic
      ./release.sh # retail
    fi

branches:
  only:
    - master
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/ # v1.0.0 or 1.0.0 etc

# Deploy LDoc generated pages to Github Pages on tagged release
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH
  keep-history: true
  local-dir: doc/
  on:
    tags: true
    all_branches: true
    condition: ($TRAVIS_BRANCH == "master" || -n $TRAVIS_TAG) && $TRAVIS_PULL_REQUEST == "false"

notifications:
  email:
    on_failure: always
    on_success: never
