language: minimal
sudo: true

addons:
  apt:
    packages:
      - luarocks

install:
  - luarocks install --local luacheck
  - sudo luarocks install luafilesystem
  - sudo luarocks install penlight
  - curl -L -s https://github.com/stevedonovan/LDoc/archive/1.4.6.tar.gz | tar -xz
  - curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh

script:
  - |
    if [ "$TRAVIS_BRANCH" == "master" ]; then
      /home/travis/.luarocks/bin/luacheck DRList-1.0.lua tests/test.lua
      lua tests/test.lua
    fi
  - |
    if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" -a -n "$TRAVIS_TAG" ]; then
      rm -rf libs # libs/ is kept before so tests.lua works, but we need to remove it here to make nolib-creation work with packager script below
      lua LDoc-1.4.6/ldoc.lua DRList-1.0.lua
      chmod +x ./release.sh
      ./release.sh -d
      ./release.sh -d -e -s
    fi

  # TODO: curl -s https://raw.githubusercontent.com/BigWigsMods/packager/master/release.sh | bash

branches:
  only:
    - master
    - /^v?\d+\.\d+(\.\d+)?(-\S*)?$/ # v1.0.0 or 1.0.0 etc

# Deploy LDoc generated pages to Github Pages on tagged release
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_OAUTH
  keep-history: true
  local-dir: doc/
  on:
    tags: true
    all_branches: true
    condition: $TRAVIS_BRANCH == "master" && $TRAVIS_PULL_REQUEST == "false"

notifications:
  email:
    on_failure: always
    on_success: never
