name: Report missing or invalid spell ID.
description: Report a spell or category that is missing or invalid.
title: "[BUG]: "
labels: [bug]
assignees:
- wardz
body:
- type: markdown
  attributes:
    value: |
      Please make sure you're using the latest version of DRList-1.0 before reporting an issue.
      Other addons might not always contain the latest updated libraries.
- type: textarea
  id: what-spell
  attributes:
    label: Which spells or categories are invalid?
    description: Does the spells trigger DR incorrectly, or do they never trigger at all?
  validations:
    required: true
- type: dropdown
  id: version
  attributes:
    label: Game Version
    description: Which versions of World of Warcraft are you experiencing the issue for?
    multiple: true
    options:
      - Retail
      - The Burning Crusade Classic
      - Classic Era
  validations:
    required: true
- type: dropdown
  id: language
  attributes:
    label: Game Language
    description: What language is your World of Warcraft client running?
    multiple: true
    options:
      - English
      - French
      - German
      - Italian
      - Korean
      - Chinese
      - Russian
      - Spanish
      - Brazil
  validations:
    required: true
