name: CI

on:
  push:
    tags:
      - "v*"
      - "!**-alpha**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Luacheck tests
        uses: nebularg/actions-luacheck@v1
        with:
          args: --quiet

      - name: Run all personal tests
        run: |
          lua DRList-1.0/tests/test-classic.lua
          lua DRList-1.0/tests/test-tbc.lua
          lua DRList-1.0/tests/test-wotlk.lua
          lua DRList-1.0/tests/test-retail.lua

      - name: Check if minor versions matches
        run: |
          version_file1=$(sed -n 's/local MAJOR, MINOR = "DRList-1.0", \(.*\)--.*/\1/p' DRList-1.0/DRList-1.0.lua)
          version_file2=$(sed -n 's/local MAJOR, MINOR = "DRList-1.0", \(.*\)--.*/\1/p' DRList-1.0/Spells.lua)
          if [ "$version_file1" != "$version_file2" ]; then
            echo "::error::DRList-1.0.lua minor version does not match Spells.lua version."
          fi

      - name: Install and generate ldocs
        run: |
          curl -L -s https://github.com/stevedonovan/LDoc/archive/1.4.6.tar.gz | tar -xz
          sudo luarocks install luafilesystem
          sudo luarocks install penlight
          lua LDoc-1.4.6/ldoc.lua DRList-1.0/DRList-1.0.lua

      - name: Deploy docs to Github Pages
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: doc

      - name: Create and deploy packages
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
